### ISSUE TITLE
Provide meaningful error messages

### ISSUE THREAD

**Issue by Drafter500** [chaos-adept/big-bro#7]
I get this error when something is wrong with connection: 

```
Unhandled rejection TypeError: Cannot read property 'worklogs' of undefined
    at C:\sc\big-bro\lib\worklog-fetch.js:64:64
    at next (native)
    at tryCatcher (C:\sc\big-bro\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\sc\big-bro\node_modules\bluebird\js\release\generators.js:97:49)
    at Promise._settlePromise (C:\sc\big-bro\node_modules\bluebird\js\release\promise.js:574:26)
    at Promise._settlePromise0 (C:\sc\big-bro\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\sc\big-bro\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (C:\sc\big-bro\node_modules\bluebird\js\release\promise.js:638:18)
    at PromiseArray._resolve (C:\sc\big-bro\node_modules\bluebird\js\release\promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (C:\sc\big-bro\node_modules\bluebird\js\release\promise_array.js:144:14)
    at Promise._settlePromise (C:\sc\big-bro\node_modules\bluebird\js\release\promise.js:574:26)
    at Promise._settlePromise0 (C:\sc\big-bro\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\sc\big-bro\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (C:\sc\big-bro\node_modules\bluebird\js\release\promise.js:638:18)
    at C:\sc\big-bro\node_modules\bluebird\js\release\nodeback.js:42:21
    at Request._callback (C:\sc\big-bro\node_modules\chaos-adept-jira\lib\jira.js:1632:17)
```

It would be good to handle it and provide user with more meaningful message

**Comment by chaos-adept** [comment]
it seems that `getWorkLogPromise = Promise.promisify(jira.getWorklog.bind(jira));` returns undefined from a promise without rasing exception flow in the promise chain.

the possible reason could be empty  http responses with status 200 from the jira instance

it make sense to improve logging by adding catch to the getResult 52bc1666f9353a902a377faf651b2c4c0511bea9  worklog-fetch.js:87 , for now it makes sense to reduce efforts just by throwing unexpected response error

**Comment by chaos-adept** [comment]
feature of repeatable requesting worklogs has been added, currently it is possible to configure how much time jira client makes attempts to fetch data:
config.default.js:17

> issueFetchAttemptCount: 5,
